name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  main:
    uses: ./.github/setup

    steps:
      - name: Find Git SHAs for affected tasks
        uses: nrwl/nx-set-shas@v4

      - name: Run affected tasks
        run: pnpm affected

      - name: Publish Test Results
        if: ${{ hashFiles('dist/test-results/') != '' }}
        uses: bibipkins/dotnet-test-reporter@v1.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: 'Unit Test Results'
          results-path: ./dist/test-results/*.trx
          coverage-path: ./dist/test-results/**/coverage.opencover.xml
          coverage-threshold: 90
