name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    uses: ./.github/setup

    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: pnpm release
